/*

PROBLEM LINK : https://bit.ly/33hi3MB

Given a string, we have to find out all its subsequences of it.
A String is a subsequence of a given String, 
that is generated by deleting some character of a given string without changing its order.


SAMPLE INPUT  : abc
SAMPLE OUTPUT : a, b, c, ab, bc, ac, abc.

*/
#include<iostream>
#include<vector>
using namespace std;
void sum_subset(string& arr , int i , string s , vector<string> &result){
    if(i==arr.length()){
        if(s.length()>0)   result.push_back(s);
        return;
    }
    sum_subset(arr,i+1,s+arr[i],result);  // ELEMENT WILL BE PRESENT IN SUBSET
    sum_subset(arr,i+1,s,result);         // ELEMENT WILL NOT BE PRESENT IN SUBSET

}
int main(){
    string s;
    cout<<"Enter The String : ";
    cin>>s;
    vector<string> result;
    sum_subset(s,0,"",result);

    for(auto i : result) cout<<i<<" ";
    cout<<"length of result : "<<result.size();



    return 0;
}